# fly.toml app configuration file generated for malvin-xd-bx7w8g on 2025-05-23T15:06:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'malvin-xd-bx7w8g'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
